# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Ronvu' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ronvu
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'MGSwipeTableCell'
    # pod 'GeoFire', '>= 1.1.3'

end
